//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCellPhoneRMEntities : DbContext
    {
        public DBCellPhoneRMEntities()
            : base("name=DBCellPhoneRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerTbl> CustomerTbl { get; set; }
        public virtual DbSet<PackTbl> PackTbl { get; set; }
        public virtual DbSet<SubscriberPacksTbl> SubscriberPacksTbl { get; set; }
        public virtual DbSet<SubscriberTbl> SubscriberTbl { get; set; }
    }
}
