//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberPacksTbl
    {
        public int IdSubscriber { get; set; }
        public int IdPack { get; set; }
        public Nullable<int> UsingMinutes { get; set; }
    
        public virtual PackTbl PackTbl { get; set; }
        public virtual SubscriberTbl SubscriberTbl { get; set; }
    }
}
