//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriberTbl()
        {
            this.SubscriberPacksTbl = new HashSet<SubscriberPacksTbl>();
        }
    
        public int IdSubscriber { get; set; }
        public string NameSubscriber { get; set; }
        public Nullable<int> IdCustomer { get; set; }
    
        public virtual CustomerTbl CustomerTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriberPacksTbl> SubscriberPacksTbl { get; set; }
    }
}
